Use java.net.URI instead of com.netaporter.uri.Uri.
This is because netaporter-uri pulls in scala-compiler which was causing:
:scrud:sample-app-android:packageDebug
Error: duplicate files during packaging of APK /home/eric/PabstSoftware/git/android-apps/scrud/sample-app-android/build/outputs/apk/sample-app-android-debug-unaligned.apk
	Path in archive: rootdoc.txt
	Origin 1: /home/eric/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-compiler/2.10.3/fc9759d060ae131a73c020d477e25a14534cbedd/scala-compiler-2.10.3.jar
	Origin 2: /home/eric/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.10.3/21d99cee3d3e478255ef9fcc90b571fb2ab074fc/scala-library-2.10.3.jar
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'rootdoc.txt'
	  }
	}